# Usar una imagen oficial de Node ligera
FROM node:22-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de configuración de dependencias
COPY package.json package-lock.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto del código del frontend
COPY . .

# Exponer el puerto por defecto de Vite
EXPOSE 5173

# Comando para levantar el servidor de desarrollo exponiendo la red
CMD ["npm", "run", "dev", "--", "--host"]